[back to [index.ipynb](index.ipynb)]

# 1. Re-compute the speed of light from Michelson's instrument readings

In [1]:
import mammos_entity as me

In [2]:
data = me.from_csv("data/michelson-1879-entities.csv")

In [3]:
data

EntityCollection(
    description='Michelson\'s 1879 determination of the speed of light: the instrument readings.\n\nA. A. Michelson, "Experimental Determination of the Velocity of Light", Astronomical Papers of the American Ephemeris 1 (1880) 109-145. 100 observations made at the U.S. Naval Academy, Annapolis, 5 June - 2 July 1879. Transcribed via the R package loon.data (michelson_1879); see also MacKay and Oldford, Statistical Science 15(3) 254-278 (2000), doi:10.1214/ss/1009212817.\n\nRotating-mirror method. Light travels from the revolving mirror to a fixed mirror and back while the mirror turns; the returned beam is deflected by twice the mirror rotation and read at radial distance r as a displacement d, giving c = 8 * pi * N * D * r / d\n\nThe apparatus constant D is the separation of the revolving and the fixed mirror. It is not part of the observation table and is recorded only here: D = 1986.23 ft = 605.4029 m\n\nThe revolving mirror rotates with frequence N. The speed of light is not stored in this file: it is derived from these readings. Note that the light travelled in air, not in vacuum.',
    N=Entity(ontology_label='Frequency', value=array([257.36 257.52 257.52 ... 128.63 96.48 64.32]) (shape=(100,)), unit='Hz', description='Rotation rate of the revolving mirror, in revolutions per second, timed against a tuning fork. '),
    r=Entity(ontology_label='RadialDistance', value=array([8.7392256 8.734044 8.7316056 ... 10.120884 10.120884 10.120884]) (shape=(100,)), unit='m', description='Distance from the axis of the revolving mirror to the crosshair of the micrometer.'),
    screw_turns=Entity(ontology_label='AngularDisplacement', value=array([114.55 114.56 114.5 ... 66.34 49.76 33.17]) (shape=(100,)), description='Rotation of the micrometer screw between the setting on the slit and the setting on the deflected image. Measured in in turns of the screw, not necessarily a whole number. Dimensionless.'),
    screw_pitch=Entity(ontology_label='Length', value=array([0.00099614 0.00099614 0.00099614 ... 0.00099586 0.0009958 0.00099574]) (shape=(100,)), unit='m', description='Travel of the micrometer crosshair per one full turn of the screw. Recorded in millimetres per turn. The pitch varies along the screw, hence one calibration value per observation. EMMO has no term for screw pitch; Length is the closest I could find.'),
    d=Entity(ontology_label='Distance', value=array([0.11410784 0.1141178 0.11405803 ... 0.06606535 0.04955101 0.0330287]) (shape=(100,)), unit='m', description='Separation of the slit and the deflected image, obtained as screw_turns * screw_pitch. '),
)

In [4]:
data.N  # expand by clickling on [+] - only in live version of notebook

Entity(ontology_label='Frequency', value=array([257.36, 257.52, 257.52, 193.14, 193.14, 257.42, 257.39, 257.39,
       257.39, 257.39, 257.39, 257.29, 257.29, 257.45, 257.45, 257.45,
       257.49, 257.49, 257.49, 257.42, 257.42, 257.42, 257.42, 257.42,
       258.7 , 255.69, 257.58, 257.6 , 257.59, 257.57, 257.56, 257.36,
       257.33, 257.32, 257.32, 257.32, 257.62, 257.59, 257.58, 257.43,
       257.43, 257.43, 257.43, 257.43, 257.65, 257.65, 257.62, 257.43,
       257.43, 257.43, 257.65, 257.63, 257.62, 257.61, 257.36, 257.4 ,
       257.39, 257.39, 257.38, 257.38, 257.65, 257.64, 257.63, 257.61,
       257.6 , 257.42, 257.38, 257.37, 257.38, 257.38, 257.32, 257.33,
       257.32, 257.3 , 257.29, 257.5 , 257.49, 257.48, 257.47, 257.45,
       257.33, 257.33, 257.46, 257.44, 257.43, 257.42, 257.42, 257.42,
       193.  , 193.  , 193.  , 193.  , 257.35, 257.34, 257.28, 257.28,
       192.95, 128.63,  96.48,  64.32]), unit='Hz', description='Rotation rate of the revolving mirror, in revolutions per second, timed against a tuning fork. ')

In [5]:
# explore data object - can get to the underlying quantity (numpy array with units)
data.N.quantity

<Quantity [257.36, 257.52, 257.52, 193.14, 193.14, 257.42, 257.39, 257.39,
           257.39, 257.39, 257.39, 257.29, 257.29, 257.45, 257.45, 257.45,
           257.49, 257.49, 257.49, 257.42, 257.42, 257.42, 257.42, 257.42,
           258.7 , 255.69, 257.58, 257.6 , 257.59, 257.57, 257.56, 257.36,
           257.33, 257.32, 257.32, 257.32, 257.62, 257.59, 257.58, 257.43,
           257.43, 257.43, 257.43, 257.43, 257.65, 257.65, 257.62, 257.43,
           257.43, 257.43, 257.65, 257.63, 257.62, 257.61, 257.36, 257.4 ,
           257.39, 257.39, 257.38, 257.38, 257.65, 257.64, 257.63, 257.61,
           257.6 , 257.42, 257.38, 257.37, 257.38, 257.38, 257.32, 257.33,
           257.32, 257.3 , 257.29, 257.5 , 257.49, 257.48, 257.47, 257.45,
           257.33, 257.33, 257.46, 257.44, 257.43, 257.42, 257.42, 257.42,
           193.  , 193.  , 193.  , 193.  , 257.35, 257.34, 257.28, 257.28,
           192.95, 128.63,  96.48,  64.32] Hz>

In [6]:
# Constant D defined in free text description above

import mammos_units as u
D = 605.4029 * u.m

In [7]:
# we need pi
import math
pi = math.pi

In [8]:
# extract (quantity) data from data set 

N = data.N.quantity  # numpy array with units
r = data.r.q  # .q is abbreviation for .quantity
d = data.d.q
# compute speed of light using equation from metadata
c = 8 * pi * N * D * r / d
c

<Quantity [2.99904431e+08, 2.99886773e+08, 2.99960152e+08, 3.00130663e+08,
           2.99987357e+08, 2.99796523e+08, 3.00002453e+08, 3.00028663e+08,
           3.00044326e+08, 2.99944781e+08, 3.00054545e+08, 3.00037378e+08,
           2.99984988e+08, 2.99700549e+08, 2.99805065e+08, 2.99857351e+08,
           3.00035679e+08, 3.00035679e+08, 3.00009026e+08, 3.00017996e+08,
           3.00017996e+08, 2.99991345e+08, 3.00017996e+08, 2.99991345e+08,
           2.99660889e+08, 2.99536313e+08, 2.99900829e+08, 2.99924115e+08,
           2.99965766e+08, 2.99889186e+08, 2.99877543e+08, 2.99852374e+08,
           2.99870722e+08, 2.99965723e+08, 2.99939052e+08, 2.99885725e+08,
           2.99862162e+08, 2.99853875e+08, 2.99815603e+08, 2.99859330e+08,
           2.99939286e+08, 2.99939286e+08, 2.99939286e+08, 2.99912629e+08,
           2.99774608e+08, 2.99774608e+08, 2.99686492e+08, 2.99923280e+08,
           3.00029939e+08, 3.00003267e+08, 2.99929009e+08, 2.99958972e+08,
           2.99894086e+08, 2.99909063e+08, 2.99886702e+08, 2.99888287e+08,
           2.99899146e+08, 2.99854129e+08, 2.99887494e+08, 2.99887494e+08,
           2.99927452e+08, 2.99870816e+08, 2.99859177e+08, 2.99858392e+08,
           2.99846752e+08, 2.99821683e+08, 2.99820109e+08, 2.99785952e+08,
           2.99797600e+08, 2.99820109e+08, 2.99952679e+08, 2.99986864e+08,
           2.99930154e+08, 2.99929365e+08, 2.99917708e+08, 2.99838387e+08,
           2.99894287e+08, 2.99905161e+08, 2.99893513e+08, 2.99825185e+08,
           2.99932885e+08, 2.99887840e+08, 2.99827770e+08, 2.99849494e+08,
           2.99815338e+08, 2.99848711e+08, 2.99826200e+08, 2.99848711e+08,
           2.99845890e+08, 2.99875974e+08, 2.99906063e+08, 2.99906063e+08,
           2.99826163e+08, 2.99769427e+08, 2.99938124e+08, 2.99960676e+08,
           2.99955824e+08, 2.99827399e+08, 2.99838644e+08, 2.99886845e+08] Hz m>

In [9]:
# We want the mean:
c.mean()

In [10]:
# in m/s
c.mean().to("m/s")
# export to pandas

In [11]:
# or km/s
c.mean().to("km/s")

In [12]:
# Note: for those knowing pandas, we can get 
# the data into a dataframe, and compute c there 
# (although not computing with units)
data.to_dataframe()

         N          r  screw_turns  screw_pitch         d
0   257.36   8.739226       114.55     0.000996  0.114108
1   257.52   8.734044       114.56     0.000996  0.114118
2   257.52   8.731606       114.50     0.000996  0.114058
3   193.14   8.731606        85.84     0.000996  0.085495
4   193.14   8.732520        85.89     0.000996  0.085545
..     ...        ...          ...          ...       ...
95  257.28  10.153193       133.00     0.000996  0.132504
96  192.95  10.120884        99.45     0.000996  0.099058
97  128.63  10.120884        66.34     0.000996  0.066065
98   96.48  10.120884        49.76     0.000996  0.049551
99   64.32  10.120884        33.17     0.000996  0.033029

[100 rows x 5 columns]

In [13]:
# with units in header if desired
data.to_dataframe(include_units=True)

    N (Hz)      r (m)  screw_turns  screw_pitch (m)     d (m)
0   257.36   8.739226       114.55         0.000996  0.114108
1   257.52   8.734044       114.56         0.000996  0.114118
2   257.52   8.731606       114.50         0.000996  0.114058
3   193.14   8.731606        85.84         0.000996  0.085495
4   193.14   8.732520        85.89         0.000996  0.085545
..     ...        ...          ...              ...       ...
95  257.28  10.153193       133.00         0.000996  0.132504
96  192.95  10.120884        99.45         0.000996  0.099058
97  128.63  10.120884        66.34         0.000996  0.066065
98   96.48  10.120884        49.76         0.000996  0.049551
99   64.32  10.120884        33.17         0.000996  0.033029

[100 rows x 5 columns]